### ISSUE TITLE
Groupquota not work if enabled Mail app

### ISSUE THREAD

**Issue by phivinhngoc** [nextcloud/groupquota#14] opened 2020-12-16 02:41 UTC
OS : Debian 10
webserver : apache2
database : mysql
php version : 7.4
---------------------------------------------
Nextcloud version : 20.0.3 (latest)
Mail version : 1.7.2 (latest)
Groupquota version : 0.1.4 (latest)
Groupquota not work if Installed mail app.
---------------------------------------------
* command : `sudo -u www-data php /var/www/html/nextcloud/occ groupquota:get "Khac"`
* return code :
```
An unhandled exception has been thrown:
TypeError: Return value of "OCA\GroupQuota\Command\GetQuota::execute()" must be of the type int, "null" returned. in /var/www/html/nextcloud/apps/mail/vendor/symfony/console/Command/Command.php:261
Stack trace:
#0 /var/www/html/nextcloud/core/Command/Base.php(169): Symfony\Component\Console\Command\Command->run()
#1 /var/www/html/nextcloud/apps/mail/vendor/symfony/console/Application.php(920): OC\Core\Command\Base->run()
#2 /var/www/html/nextcloud/apps/mail/vendor/symfony/console/Application.php(266): Symfony\Component\Console\Application->doRunCommand()
#3 /var/www/html/nextcloud/apps/mail/vendor/symfony/console/Application.php(142): Symfony\Component\Console\Application->doRun()
#4 /var/www/html/nextcloud/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run()
#5 /var/www/html/nextcloud/console.php(100): OC\Console\Application->run()
#6 /var/www/html/nextcloud/occ(11): require_once('/var/www/html/n...')
```

**Comment by jim005** [comment] 2020-12-17 13:09
+1  ! Same issue.

**Comment by joshtrichards** [comment] 2024-09-23 22:21
Duplicate of #11 (and also fixed along time ago).

**Closed by joshtrichards** 2024-09-23 22:21 UTC
Labels: bug
